// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clnichbxibxujrfgogtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbmljaGJ4aWJ4dWpyZmdvZ3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTMyNjYsImV4cCI6MjA1NTgyOTI2Nn0.aUwjBHEdG4QrMseZ_Zkk5sJNavEJ-Ydql3vxkurgfmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);